# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DejaCanary < Formula
  desc "Predictive inline shell autosuggestions for zsh (canary branch)"
  homepage "https://github.com/Serubin/deja"
  version "0.4.1-canary.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Serubin/deja/releases/download/0.4.1-canary.3/deja_0.4.1-canary.3_darwin_amd64.tar.gz"
      sha256 "3ed46c5c7e51ea86856be78d54fd1dc4174cde56afbaec22f581f1cc0e76ba79"

      define_method(:install) do
        if build.head?
          revision = Utils.git_head(safe: true) || "unknown"
          revision = revision[0, 7]

          ldflags = %W[
            -s -w
            -X main.version=canary-#{revision}
            -X main.commit=#{revision}
            -X main.date=#{time.iso8601}
          ]

          # CGO is required: the SQLite driver is mattn/go-sqlite3.
          ENV["CGO_ENABLED"] = "1"
          # output: is explicit because std_go_args names the binary after the
          # formula, which would install `deja-canary`. The command is `deja`.
          system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"deja"), "./cmd/deja"
        else
          bin.install "deja"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Serubin/deja/releases/download/0.4.1-canary.3/deja_0.4.1-canary.3_darwin_arm64.tar.gz"
      sha256 "ca876a78983d916cb8be1a39c88ea3a5a2ac0364b00f2fb8705c2ef3955f450e"

      define_method(:install) do
        if build.head?
          revision = Utils.git_head(safe: true) || "unknown"
          revision = revision[0, 7]

          ldflags = %W[
            -s -w
            -X main.version=canary-#{revision}
            -X main.commit=#{revision}
            -X main.date=#{time.iso8601}
          ]

          # CGO is required: the SQLite driver is mattn/go-sqlite3.
          ENV["CGO_ENABLED"] = "1"
          # output: is explicit because std_go_args names the binary after the
          # formula, which would install `deja-canary`. The command is `deja`.
          system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"deja"), "./cmd/deja"
        else
          bin.install "deja"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Serubin/deja/releases/download/0.4.1-canary.3/deja_0.4.1-canary.3_linux_amd64.tar.gz"
      sha256 "8e323ff3b494c61182af2d9687e91744a23e3b52fecc6572466f1e987bbd69f6"
      define_method(:install) do
        if build.head?
          revision = Utils.git_head(safe: true) || "unknown"
          revision = revision[0, 7]

          ldflags = %W[
            -s -w
            -X main.version=canary-#{revision}
            -X main.commit=#{revision}
            -X main.date=#{time.iso8601}
          ]

          # CGO is required: the SQLite driver is mattn/go-sqlite3.
          ENV["CGO_ENABLED"] = "1"
          # output: is explicit because std_go_args names the binary after the
          # formula, which would install `deja-canary`. The command is `deja`.
          system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"deja"), "./cmd/deja"
        else
          bin.install "deja"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Serubin/deja/releases/download/0.4.1-canary.3/deja_0.4.1-canary.3_linux_arm64.tar.gz"
      sha256 "29dc1905e794421d47aa384894b4ed532bd12c3e57034b3cf02e1e0b479b5672"
      define_method(:install) do
        if build.head?
          revision = Utils.git_head(safe: true) || "unknown"
          revision = revision[0, 7]

          ldflags = %W[
            -s -w
            -X main.version=canary-#{revision}
            -X main.commit=#{revision}
            -X main.date=#{time.iso8601}
          ]

          # CGO is required: the SQLite driver is mattn/go-sqlite3.
          ENV["CGO_ENABLED"] = "1"
          # output: is explicit because std_go_args names the binary after the
          # formula, which would install `deja-canary`. The command is `deja`.
          system "go", "build", *std_go_args(ldflags: ldflags, output: bin/"deja"), "./cmd/deja"
        else
          bin.install "deja"
        end
      end
    end
  end

  # All three install a `deja` binary into the same prefix. They also share
  # ~/.local/share/deja, and deja bakes the absolute path of the binary that
  # generated init.zsh into it, so two installed copies would each see the
  # other's stamp as stale and regenerate the script on every shell.
  conflicts_with "deja-main", because: "both install a `deja` binary"
  conflicts_with "giammarco-ferranti/deja/deja", because: "both install a `deja` binary"

  # Retained so `brew install --HEAD` still builds the tip of canary, ahead
  # of whatever the last canary release was:
  #
  #   brew install --HEAD serubin/tools/deja-canary
  #   brew upgrade --fetch-HEAD serubin/tools/deja-canary
  #
  # Go is a build dependency of that path only — the default install is a
  # prebuilt binary.
  head do
    url "https://github.com/Serubin/deja.git", branch: "canary"
    depends_on "go" => :build
  end

  def caveats
    <<~EOS
      This is the canary build — a prebuilt binary from the tip of the `canary`
      branch as of 0.4.1-canary.3, ahead of the released `deja`. Use
      `brew install --HEAD serubin/tools/deja-canary` to build the branch tip
      from source instead.

      It shares ~/.local/share/deja with the other deja formulae, including the
      history database, so switching between them keeps your history.

      Import your existing zsh history once:

        deja import

      Then add this to your ~/.zshrc:

        if [[ -r "$HOME/.local/share/deja/init.zsh" ]]; then
          source "$HOME/.local/share/deja/init.zsh"
        else
          eval "$(deja init zsh)"
        fi

      The daemon outlives shell sessions, so after installing or upgrading,
      replace the running one:

        deja daemon --restart
    EOS
  end

  test do
    assert_match "deja", shell_output("#{bin}/deja version")

    # An end-to-end exercise of the real paths: import a history file, then
    # ask for a suggestion. This runs with the daemon down, so it covers the
    # direct SQLite fallback rather than just argument parsing.
    ENV["HOME"] = testpath
    (testpath/"history").write <<~EOS
      : 1700000001:0;git status
      : 1700000002:0;git commit --amend
    EOS

    system bin/"deja", "import", "--file", testpath/"history"
    assert_match "git commit --amend",
      shell_output("#{bin}/deja query --buffer 'git com' --dir #{testpath}")

    # Canary carries the zsh/net/socket transport, so the generated
    # integration script must contain the socket path substitution and the
    # zsocket probe.
    system bin/"deja", "init", "zsh"
    init_script = testpath/".local/share/deja/init.zsh"
    assert_path_exists init_script
    assert_match "zsocket", init_script.read
    # No unsubstituted placeholders left in the script. Spelled as an escaped
    # regex because GoReleaser runs the assembled formula through its template
    # engine, which would try to interpret a literal brace pair here.
    refute_match(/\{\{/, init_script.read)
  end
end
