# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deja < Formula
  desc "Predictive inline shell autosuggestions for zsh (canary builds)"
  homepage "https://github.com/Serubin/deja"
  version "0.4.1-canary.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Serubin/deja/releases/download/0.4.1-canary.5/deja_0.4.1-canary.5_darwin_amd64.tar.gz"
      sha256 "3085be80724e4be50f5ebc245e169f0510cfeff4532493c10c11af5b6ad2cdb8"

      define_method(:install) do
        if build.head?
          revision = Utils.git_head(safe: true) || "unknown"
          revision = revision[0, 7]

          ldflags = %W[
            -s -w
            -X main.version=canary-#{revision}
            -X main.commit=#{revision}
            -X main.date=#{time.iso8601}
          ]

          # CGO is required: the SQLite driver is mattn/go-sqlite3.
          ENV["CGO_ENABLED"] = "1"
          system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/deja"
        else
          bin.install "deja"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Serubin/deja/releases/download/0.4.1-canary.5/deja_0.4.1-canary.5_darwin_arm64.tar.gz"
      sha256 "96fa146a9b2ad67a5207860ce574144555daeac3d4eef1c84acee317e01edd25"

      define_method(:install) do
        if build.head?
          revision = Utils.git_head(safe: true) || "unknown"
          revision = revision[0, 7]

          ldflags = %W[
            -s -w
            -X main.version=canary-#{revision}
            -X main.commit=#{revision}
            -X main.date=#{time.iso8601}
          ]

          # CGO is required: the SQLite driver is mattn/go-sqlite3.
          ENV["CGO_ENABLED"] = "1"
          system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/deja"
        else
          bin.install "deja"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Serubin/deja/releases/download/0.4.1-canary.5/deja_0.4.1-canary.5_linux_amd64.tar.gz"
      sha256 "2fb51b3c3ca053e78ca724d0c785a229b6ac3f74a0b0f721505afeb34b8b85ef"
      define_method(:install) do
        if build.head?
          revision = Utils.git_head(safe: true) || "unknown"
          revision = revision[0, 7]

          ldflags = %W[
            -s -w
            -X main.version=canary-#{revision}
            -X main.commit=#{revision}
            -X main.date=#{time.iso8601}
          ]

          # CGO is required: the SQLite driver is mattn/go-sqlite3.
          ENV["CGO_ENABLED"] = "1"
          system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/deja"
        else
          bin.install "deja"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Serubin/deja/releases/download/0.4.1-canary.5/deja_0.4.1-canary.5_linux_arm64.tar.gz"
      sha256 "f90c5f14e32247e304b7f4ba8b4b78b136bf16b7a86824dc03d3f730e5a995dd"
      define_method(:install) do
        if build.head?
          revision = Utils.git_head(safe: true) || "unknown"
          revision = revision[0, 7]

          ldflags = %W[
            -s -w
            -X main.version=canary-#{revision}
            -X main.commit=#{revision}
            -X main.date=#{time.iso8601}
          ]

          # CGO is required: the SQLite driver is mattn/go-sqlite3.
          ENV["CGO_ENABLED"] = "1"
          system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/deja"
        else
          bin.install "deja"
        end
      end
    end
  end

  # Both install a `deja` binary into the same prefix. They also share
  # ~/.local/share/deja, and deja bakes the absolute path of the binary that
  # generated init.zsh into it, so two installed copies would each see the
  # other's stamp as stale and regenerate the script on every shell.
  conflicts_with "giammarco-ferranti/deja/deja", because: "both install a `deja` binary"

  # Retained so `brew install --HEAD` still builds the tip of canary, ahead
  # of whatever the last canary release was:
  #
  #   brew install --HEAD serubin/formula/deja
  #   brew upgrade --fetch-HEAD serubin/formula/deja
  #
  # Go is a build dependency of that path only — the default install is a
  # prebuilt binary.
  head do
    url "https://github.com/Serubin/deja.git", branch: "canary"
    depends_on "go" => :build
  end

  def caveats
    <<~EOS
      This is the canary build — a prebuilt binary from the tip of the `canary`
      branch as of 0.4.1-canary.5, ahead of the released `deja`. Use
      `brew install --HEAD serubin/formula/deja` to build the branch tip
      from source instead.

      It shares ~/.local/share/deja with the upstream `deja` formula, including
      the history database, so switching between them keeps your history.

      Import your existing zsh history once:

        deja import

      Then add this to your ~/.zshrc:

        if [[ -r "$HOME/.local/share/deja/init.zsh" ]]; then
          source "$HOME/.local/share/deja/init.zsh"
        else
          eval "$(deja init zsh)"
        fi

      The daemon outlives shell sessions, so after installing or upgrading,
      replace the running one:

        deja daemon --restart
    EOS
  end

  test do
    assert_match "deja", shell_output("#{bin}/deja version")

    # An end-to-end exercise of the real paths: import a history file, then
    # ask for a suggestion. This runs with the daemon down, so it covers the
    # direct SQLite fallback rather than just argument parsing.
    ENV["HOME"] = testpath
    (testpath/"history").write <<~EOS
      : 1700000001:0;git status
      : 1700000002:0;git commit --amend
    EOS

    system bin/"deja", "import", "--file", testpath/"history"
    assert_match "git commit --amend",
      shell_output("#{bin}/deja query --buffer 'git com' --dir #{testpath}")

    # Canary carries the zsh/net/socket transport, so the generated
    # integration script must contain the socket path substitution and the
    # zsocket probe.
    system bin/"deja", "init", "zsh"
    init_script = testpath/".local/share/deja/init.zsh"
    assert_path_exists init_script
    assert_match "zsocket", init_script.read
    # No unsubstituted placeholders left in the script. Spelled as an escaped
    # regex because GoReleaser runs the assembled formula through its template
    # engine, which would try to interpret a literal brace pair here.
    refute_match(/\{\{/, init_script.read)
  end
end
